040 login system
omcmenamin/Belfast_Team2_Frontend pull request #4
Opened 2023-09-19 10:14 UTC by MylesScullion

Login system for the frontend

2023-09-19 10:28 UTC, glenn-hamilton commented on app.ts
> +app.use(session({secret: 'NOT HARDCODED SECRET', cookie: {maxAge: 60000}}));
Your secret shouldn't be hard coded, it should be passed via an environment variable

2023-09-19 10:28 UTC, glenn-hamilton commented on controller/authController.ts
> +            res.cookie('jwtToken', jwtToken, { maxAge: 3600000, httpOnly: true });
How'd you come to this `maxAge` value?

2023-09-19 10:28 UTC, glenn-hamilton commented on model/employees.ts
This file is empty

2023-09-19 10:28 UTC, glenn-hamilton commented on package.json
> +  "main": "index.js",
Should this be `app.js`?

2023-09-19 10:28 UTC, glenn-hamilton commented on service/authService.ts
> +        // if(e.response.status === 401){
Is this still needed?

2023-09-19 10:28 UTC, glenn-hamilton commented on service/authService.ts
> +        const response= await axios.post('http://localhost:8080/api/login', login)
This hard coded URL won't work correctly when deployed to AWS

2023-09-19 10:28 UTC, glenn-hamilton commented on service/authService.ts
> +        const response= await axios.post('http://localhost:8080/api/register', user)
Same with this URL

2023-09-19 10:28 UTC, glenn-hamilton commented on controller/authController.ts
> +    app.post('/register', async (req: Request, res: Response)=> {
There is no positive feedback to the user here to let them know that their account has been successfully created

2023-09-19 10:28 UTC, glenn-hamilton commented on service/authService.ts
> +        throw new Error ('Registration failure')
This error isn't very useful to the user

2023-09-20 08:56 UTC, shaunganley requested changes
really impressive stuff. Just 2 comments on how you're passing the request body using axios. You will also need to add some unit and UI tests

2023-09-20 08:56 UTC, shaunganley commented on service/authService.ts
> +        const response= await axios.post(process.env.URL+'/login/'+login)
```suggestion
        const response= await axios.post(process.env.URL+'/login/', login)
```

2023-09-20 08:56 UTC, shaunganley commented on service/authService.ts
> +        const response= await axios.post(process.env.URL+'/register/'+user)
```suggestion
        const response= await axios.post(process.env.URL+'/register/', user)
```

2023-09-21 10:02 UTC, shaunganley requested changes
still needs unit tests for service

2023-09-21 10:02 UTC, shaunganley commented on Validator/RegisterValidatorTest.ts
> +module.exports.validateRegister = function (register: Register): string {
this is identical to validateLogin method

2023-09-21 10:02 UTC, shaunganley commented on controller/authController.ts
> +            res.redirect('/login?success_msg=You are now registered and can log in');
you're not actually displaying this on the login page

2023-09-21 13:44 UTC, shaunganley requested changes
still missing tests for authService

2023-09-21 13:44 UTC, shaunganley commented on .gitignore
> +.env
duplicate

2023-09-21 13:44 UTC, shaunganley commented on Validator/Validator.ts
> +    }
duplicated code

2023-09-21 13:44 UTC, shaunganley commented on test/service/ValidateServiceTest.js
> +        validator = mock(Validator);
don't mock the validator in the validator test class

2023-09-21 13:44 UTC, shaunganley commented on test/unit/validator/LoginValidatorTest.js
> +    test('isValidLogin_EmailTooLong', () => {
can be removed

2023-09-21 13:44 UTC, shaunganley commented on test/unit/validator/RegisterValidatorTest.js
> +describe('isValidRegister', () => {
can be removed

2023-09-25 09:50 UTC, shaunganley requested changes

2023-09-25 09:50 UTC, shaunganley commented on test/unit/service/authServiceTest.ts
> +            await Login(loginData);
you're not calling your service method here to actually test it

2023-09-25 09:50 UTC, shaunganley commented on test/unit/service/authServiceTest.ts
> +            await Login(loginData);
you're not calling your service method here to actually test it

2023-09-25 09:50 UTC, shaunganley commented on test/unit/service/authServiceTest.ts
> +            await Register(registerData);
you're not calling your service method here to actually test it

2023-09-25 09:50 UTC, shaunganley commented on test/unit/service/authServiceTest.ts
> +            await Register(registerData);
you're not calling your service method here to actually test it

2023-09-26 13:02 UTC, shaunganley approved these changes

2023-09-27 11:34 UTC, omcmenamin approved these changes

2023-09-27 11:35 UTC, merged